version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ped_mais_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  web:
    build: .
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/ped_mais_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/ped_mais_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: