default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: postgres
  password: password
  database: ped_mais_development

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: postgres
  password: password
  database: ped_mais_test

production:
  url: <%= ENV["DATABASE_URL"] || "postgresql://postgres:password@localhost:5432/ped_mais_development" %>